blank_issues_enabled: false
contact_links:
  - name: Troubleshoot an Issue
    url: https://github.com/YoungFellow-le/Ps-22-Linux/discussions/categories/troubleshooting
    about: Get help with issues you're facing
  - name: Suggest a Feature
    url: https://github.com/YoungFellow-le/Ps-22-Linux/discussions/categories/ideas
    about: Have and idea that you would like to be implemented?
